### ISSUE TITLE
Fact-Finding Preparation

### ISSUE THREAD

**Issue by jordanmoore98** [the-c-team/igotacinit380#6]

**Comment by KuKhang02** [comment]
[Federated Insurance Notes.docx](https://github.com/the-c-team/igotacinit380/files/2901437/Federated.Insurance.Notes.docx)

**Comment by jordanmoore98** [comment]
[Federated Notes.pdf](https://github.com/the-c-team/igotacinit380/files/2901441/Federated.Notes.pdf)

**Comment by antonfuchs** [comment]
[Fact-Finding Notes.zip](https://github.com/the-c-team/igotacinit380/files/2901478/Fact-Finding.Notes.zip)

**Comment by jordanmoore98** [comment]
Kyle's notes... 
[KyleNotes.txt](https://github.com/the-c-team/igotacinit380/files/2901494/KyleNotes.txt)

**Comment by billvang81** [comment]
[Federate_Insurance_Notes_1_23_2019.docx](https://github.com/the-c-team/igotacinit380/files/2901538/Federate_Insurance_Notes_1_23_2019.docx)

**Comment by KuKhang02** [comment]
[Fact-Finding Question about Project Kue Khang.docx](https://github.com/the-c-team/igotacinit380/files/2901589/Fact-Finding.Question.about.Project.Kue.Khang.docx)

**Comment by antonfuchs** [comment]
[SAD Questions.docx](https://github.com/the-c-team/igotacinit380/files/2901620/SAD.Questions.docx)

**Comment by billvang81** [comment]
[Federate_insurance_questions.docx](https://github.com/the-c-team/igotacinit380/files/2901682/Federate_insurance_questions.docx)
