### ISSUE TITLE
Description of customer/client

### ISSUE THREAD

**Issue by jordanmoore98** [the-c-team/igotacinit380#8]

**Comment by billvang81** [comment]
[380_project_phase1.docx](https://github.com/the-c-team/igotacinit380/files/2911396/380_project_phase1.docx)


Description of customer/client

Detailed summary of the company or division requesting project.  This includes things to help you understand the purpose, vision and values. 

Federate Insurance would like the requesting project to focus on (MVR) motor vehicle report. Reviewing all applications from prospective clients and periodically re-evaluating current clients’ accounts. Build a system which will automatically order motor vehicle reports and ability to monitor the drivers and implement a list of drivers who are on a policy.
Company description (Who are they? What do they do?)

The company began offering life insurance, workers compensation coverage, group health insurance, estate planning services, and a variety of risk management tools. 

List of products offered by Federated Mutual Insurance Company:
•	Commercial Property and Casualty insurance 
•	Life, disability, and critical illness insurance
•	Home and auto insurance
•	Workers Compensation
Federated once offered group health insurance, but ceased this offering at the end of 2017.
Organizational chart of the company or employees who will use the system

The underwriter will use the system and to get reports to either accept a driver or decline. 

Other relevant background information available.

Federate became among the nation’s first multiline insurance companies with our expansion into liability coverage. Federate continues growing, stepping into life insurance, workers compensation coverage, group health insurance, and estate planning services. By the end of the 20th century, Federate were among the largest mutual insurance companies in the nation.  Federated started in Owatonna, a small city in southern Minnesota and servers many customers as much as 49 states.
