### ISSUE TITLE
Team Description

### ISSUE THREAD

**Issue by jordanmoore98** [the-c-team/igotacinit380#9]

**Comment by KuKhang02** [comment]
[Kue Khang Resume.docx](https://github.com/the-c-team/igotacinit380/files/2901648/Kue.Khang.Resume.docx)

**Comment by antonfuchs** [comment]
[Resume2019(2-25-2019).pdf](https://github.com/the-c-team/igotacinit380/files/2901688/Resume2019.2-25-2019.pdf)

**Comment by randallkyle** [comment]
[Resume.docx](https://github.com/the-c-team/igotacinit380/files/2915903/Resume.docx)
